# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REmdUgpHZ1XsUiZfY2IQJcfvXPIcpTLj
"""

import matplotlib.pyplot as plt

#Sample data
x=[1,2,3,4,5]
y=[5,10,15,20,25]

# Plotting
plt.plot(x,y)

#Labels and title
plt.xlabel("x-axis (Time)")
plt.ylabel("y-axis (Value)")
plt.title("Simple Line Chart")

# Show the chart
plt.show()