# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sG7BTyz0ZettivOw4o5A65wyDcTb9de
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import pandas as pd

# Sample dataset
data={
    'Experince':[1,2,3,4.5, 5], # Added a fifth experience value
    'Salary':[40000,50000,60000,70000,80000]
}
df=pd.DataFrame(data)

# Note: The original code had a typo 'Experince'.
# We will assume the intention was 'Experience' for consistency with the column selection below.
x=df[['Experince']] # Keep 'Experince' as per the dictionary key
y=df['Salary']

# Step 1: Split data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42) # Added random_state for reproducibility

# Step 2:Create model
model = LinearRegression()

# Step 3: Train
model.fit(x_train,y_train)

# Step 4: Predict
prediction=model.predict(x_test)

# Step 4: Evaluate
mse=mean_squared_error(y_test,prediction)
print("Mean Squared Error:",mse)